name: CI - CareOps+ (dev → stg → prod)

on:
  push:
    branches:
      - dev
      - stg
      - prod
      - 'feature/*'
      - aula7
      - aula8
      - aula9
  pull_request:
    branches:
      - dev
      - stg
      - prod
      - aula7
      - aula8
      - aula9

jobs:
  tests:
    name: Run unit and security tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Add aula5 dir to PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/aluno/labs/aula5:${PYTHONPATH}" >> $GITHUB_ENV
      # aulas 5 e 6
      - name: Run pytest
        run: |
            pytest -q test_security_examples.py
      
      # aulas 7.1 e 7.2
      # SAST em dev + aula7 (somente aviso)
      - name: Run Bandit (SAST) – dev/aula7 (somente aviso)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/aula7'
        run: |
          echo "Rodando Bandit (SAST) em dev/aula7 – não falha o pipeline por enquanto"
          bandit -r . -ll || true
      
      # SAST em stg/prod (gate de segurança)
      - name: Run Bandit (SAST) – stg/prod (gate de segurança)
        if: github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prod'
        run: |
          echo "Rodando Bandit (SAST) em stg/prod – falha se encontrar problemas"
          bandit -r . -ll

        # SCA em dev + aula7 (somente aviso)
      - name: Run pip-audit (SCA) – dev/aula7 (somente aviso)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/aula7'
        run: |
            echo "Rodando pip-audit (SCA) em dev/aula7 – somente aviso"
            pip-audit -r requirements.txt || true
            pip-audit -r requirements-dev.txt || true
      
        # SCA em stg/prod (gate de segurança)
      - name: Run pip-audit (SCA) – stg/prod (gate de segurança)
        if: github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prod'
        run: |
            echo "Rodando pip-audit (SCA) em stg/prod – falha em caso de vulnerabilidades"
            pip-audit -r requirements.txt
            pip-audit -r requirements-dev.txt || true

